# -*- coding: utf-8 -*-
"""iris_dtree.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Kcu3-L1iIeQG4_38woG2S60Fk5WVawuA
"""

import seaborn as sns
iris = sns.load_dataset('iris') # returns a pandas dataframe
import pandas as pd
import pandas as pd
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split

X_iris = iris.drop('species', axis=1)  
y_iris = iris['species']
xtrain, xtest, ytrain, ytest = train_test_split(xiris, yiris,random_state=1)
clf = tree.DecisionTreeClassifier()
clf = clf.fit(xtrain, ytrain)


clf.fit(xtrain, ytrain)

tree.plot_tree(clf.fit(xtrain, ytrain) )

clf.score(xtest, ytest)